/*
   THE PINS FOR THE USER INTERFACE
   BUTTONS, LEDS, SENSORS
*/

// TODO: SET THE PINS FOR THESE KNOWING THAT THESE USE MUX

#define PIXELS_PER_URBAN_PIXEL  4
#define NEO_PIXEL_PIN 2
#define NUM_URBAN_PIXELS 8 

#define PUSH_BUTTON_PINS {0,1,2,3,4,5,6,7,8}
#define LIMIT_SWITCH_PINS {0,1,2,3,4,5,6,7,8}

#define SENSOR_PINS {0,1,2,3,4,5,6,7,8}
